# Site settings
title: Bruno Temple
description: 'Hello, I`m Bruno Temple an engineer, someone who likes everything about technology and this is my site.'
url: 'http://brunotemple.com'
baseurl: '/'
google_analytics: 'UA-81849683-1'
# disqus_shortname: 'your-disqus-name'



author:
  name: 'Bruno Temple'
  email: bruno.temple@gmail.com
  twitter_username: brunotemple
  facebook_username: bruno.temple
  github_username:  brunotemple
  linkedin_username:  brunotemple

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
